"use strict";
//To create an object with keys generated by running the provided function for each key and the same values as the provided object
function transformKeys(obj, transformFn) {
    let result = {};
    for (let key in obj) {
        if (obj.hasOwnProperty(key)) {
            let newKey = transformFn(key);
            result[newKey] = obj[key];
        }
    }
    return result;
}
const originalObj = { name: "Alice", age: 25, city: "New York" };
const transformedObj = transformKeys(originalObj, key => key.toUpperCase());
console.log(transformedObj); // { NAME: 'Alice', AGE: 25, CITY: 'New York' }
